// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr7pqpYzLffqy3SKMNO7ryeBs0ekAirq4',
    appId: '1:752397717765:web:2b1b4a2efc421b9b4d676c',
    messagingSenderId: '752397717765',
    projectId: 'fluttermoviecatalog',
    authDomain: 'fluttermoviecatalog.firebaseapp.com',
    storageBucket: 'fluttermoviecatalog.appspot.com',
    measurementId: 'G-7PTFFCF7L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChC7eRYanJNk6XbOF1sESN-16dR6okrgo',
    appId: '1:752397717765:android:351887e63abd8c664d676c',
    messagingSenderId: '752397717765',
    projectId: 'fluttermoviecatalog',
    storageBucket: 'fluttermoviecatalog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIIo1qwrQWYVaPbJahTLgbZ24CkUTvWSg',
    appId: '1:752397717765:ios:0eb7e978d2aa657d4d676c',
    messagingSenderId: '752397717765',
    projectId: 'fluttermoviecatalog',
    storageBucket: 'fluttermoviecatalog.appspot.com',
    iosBundleId: 'cz.muni.fi.movieCatalog',
  );
}
